[package]
name = "d2d"
version = "0.1.0"
edition = "2021"
authors = ["Connor Power <connor@connorpower.com>"]

[dependencies]

[dependencies.windows]
version = "0.42.0"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct2D",
]

[dev-dependencies]
pretty_assertions = "1.3.0"
