name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo check --verbose
    - name: Clippy
      run: cargo clippy --verbose --tests -- -Dwarnings
    - name: Run tests
      run: cargo test --verbose
